dist: trusty
sudo: required
env:
    - SWIFT_VERSION=4.0.3
language:               node_js
node_js:
    - "node"
    - "lts/*"
    - "7"
    - "8"
before_install:
    - npm install -g npm@latest
    - npm install -g eye.js
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" # Install swift
script:
    - pwd
    - eye # JS
    - swiftc MD5/swift/hash.swift -o out # Swift MD5
    - swiftc SHA256/swift/hash.swift -o out # Swift SHA256
notifications:
  email:                false
